1:
  title: dashboard
  icon_class: null
  link_class: null
  url: /admin
  available_for: logged_in
  weight: 0
  parent: null
2:
  title: navbar
  icon_class: 'fa fa-stream'
  link_class: null
  url: /admin/navbar
  available_for: logged_in
  weight: 1
  parent: 1
3:
  title: sidebar
  icon_class: 'fa fa-stream'
  link_class: null
  url: /admin/sidebar
  available_for: logged_in
  weight: 2
  parent: 1
4:
  title: entities
  icon_class: 'fa fa-cube'
  link_class: null
  url: /admin/entity
  available_for: logged_in
  weight: 3
  parent: 1
5:
  title: tables
  icon_class: 'fa fa-table'
  link_class: null
  url: /admin/table
  available_for: logged_in
  weight: 4
  parent: 1
