table_name: blocked_ips
table_comment: 'Contains blocked IP adresses. These IP adresses can''t login to site.'
fields:
  ip:
    type: short_text
    length: '16'
    column_name: ip
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: ''
