table_name: cache
table_comment: 'Contains cached data. You can use this table via Cache class.'
fields:
  bundle:
    type: short_text
    length: '255'
    column_name: bundle
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Cache bundle.'
  key:
    type: short_text
    length: '255'
    column_name: key
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Cache key.'
  value:
    type: long_text
    column_name: value
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Cache value.'
