table_name: cache
table_comment: ''
fields:
  bundle:
    type: short_text
    length: '255'
    column_name: bundle
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: ''
  key:
    type: short_text
    length: '255'
    column_name: key
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: ''
  value:
    type: long_text
    column_name: value
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: ''
