table_name: files
table_comment: 'Contains uploaded files data.'
fields:
  file_name:
    type: short_text
    column_name: file_name
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'File original name.'
    length: '255'
  file_path:
    type: short_text
    column_name: file_path
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: true
    default: null
    comment: 'Uploaded path.'
    length: '255'
  file_size:
    type: short_text
    column_name: file_size
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'File size.'
    length: '255'
  mime_type:
    type: short_text
    column_name: mime_type
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'File mime type.'
    length: '255'
  extension:
    type: short_text
    column_name: extension
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'File extension.'
    length: '255'
  status:
    type: enumarated_list
    column_name: status
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'File is temporary or permanent.'
    values:
      temporary: temporary
      permanent: permanent
