table_name: reset_password_queue
table_comment: ''
fields:
  user:
    type: table_reference
    reference_table: users
    column_name: user
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: ''
  key:
    type: short_text
    length: '255'
    column_name: key
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: ''
