table_name: reset_password_queue
table_comment: 'Contains reset password request tokens.'
fields:
  user:
    type: table_reference
    column_name: user
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'User Id.'
    reference_table: users
  key:
    type: short_text
    column_name: key
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Reset password key.'
    length: '255'
