table_name: roles
table_comment: 'Contains roles. You can add new one.'
fields:
  role:
    type: short_text
    column_name: role
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'Role name.'
    length: '255'
