table_name: state
table_comment: 'Contains site state variable by key value association.'
fields:
  key:
    type: short_text
    column_name: key
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'State key.'
    length: '255'
  value:
    type: text
    column_name: value
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: Value.
