table_name: users_roles
table_comment: ''
fields:
  user_id:
    type: table_reference
    reference_table: users
    column_name: user_id
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: ''
  role_id:
    type: table_reference
    reference_table: roles
    column_name: role_id
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: ''
