table_name: users
table_comment: 'Contains site Users fundemantal data. Connected with User class.'
fields:
  username:
    type: short_text
    length: '20'
    column_name: username
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: Username
  name:
    type: short_text
    length: '50'
    column_name: name
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: Name
  surname:
    type: short_text
    length: '50'
    column_name: surname
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: Surname
  profile_photo:
    type: file
    reference_table: files
    column_name: profile_photo
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'User profile photo.'
  email:
    type: short_text
    length: '50'
    column_name: email
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: Email
  phone:
    type: short_text
    length: '20'
    column_name: phone
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
  password:
    type: short_text
    length: '255'
    column_name: password
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Hashed user password'
  active:
    type: checkbox
    column_name: active
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'User is active or blocked.'
  last_access:
    type: datetime
    column_name: last_access
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
