table_name: users
table_comment: 'Contains site Users fundemantal data. Connected with User class.'
fields:
  username:
    type: short_text
    column_name: username
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: Username
    length: '20'
  name:
    type: short_text
    column_name: name
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: Name
    length: '50'
  surname:
    type: short_text
    column_name: surname
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: Surname
    length: '50'
  profile_photo:
    type: file
    column_name: profile_photo
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'User profile photo.'
    reference_table: files
  email:
    type: short_text
    column_name: email
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: Email
    length: '50'
  phone:
    type: short_text
    column_name: phone
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
    length: '20'
  password:
    type: short_text
    column_name: password
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Hashed user password'
    length: '255'
  status:
    type: enumarated_list
    column_name: status
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: "Active is user can login and use the site.\r\nBlocked is user has been blocked due to too many untrested actions. Need reset password.\r\nBanned is user is not able to login to site."
    values:
      active: active
      blocked: blocked
      banned: banned
  last_access:
    type: datetime
    column_name: last_access
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
