table_name: variables
table_comment: 'Contains less secure site Variables. For more security use config.php. Connected via Variable class.'
fields:
  key:
    type: short_text
    column_name: key
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'Variable key.'
    length: '255'
  value:
    type: long_text
    column_name: value
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: Value.
  type:
    type: enumarated_list
    column_name: type
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: ''
    values:
      integer: integer
      float: float
      checkbox: checkbox
      text: text
      date: date
      datetime: datetime
      hidden: hidden
