table_name: variables
table_comment: 'Contains less secure site Variables. For more security use config.php. Connected via Variable class.'
fields:
  key:
    type: short_text
    length: '255'
    column_name: key
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'Variable key.'
  value:
    type: long_text
    column_name: value
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: Value.
