users:
  class: Src\Entity\User
  manyToMany:
    roles:
      mergeTable: "users_roles"
      selfKey: "user_id"
      foreignKey: "role_id"
      createIfNotExist: false
roles:
  class: Src\Entity\Role
translations:
  class: Src\Entity\Translation
file:
  class: Src\Entity\File
viewable_queries: 
  class: Src\Entity\ViewableQueries
variables:
  class: Src\Entity\Variable
states:
  class: Src\Entity\State
sidebar:
  class: Src\Entity\Sidebar
  manyToMany:
    roles:
      mergeTable: "sidebar_roles"
      selfKey: "sidebar_id"
      foreignKey: "role_id"
      createIfNotExist: false
navbar:
  class: Src\Entity\Navbar
  manyToMany:
    roles:
      mergeTable: "navbar_roles"
      selfKey: "navbar_id"
      foreignKey: "role_id"
      createIfNotExist: false
push_notification_subscriptions:
  class: Src\Entity\PushNotificationSubscription
